From dev/user emotions and popups
fedosovmu/mind_tracker pull request #8
Opened 2022-11-28 17:07 UTC by g1tPush

2022-11-28 17:14 UTC, g1tPush commented on lib/main.dart
> +              value: userEmotionProvider,
Оставляю комментарий

2022-11-28 17:17 UTC, fedosovmu commented on lib/main.dart
> +
Убрать пробелы

2022-11-28 17:17 UTC, fedosovmu commented on lib/src/domain/services/url_service.dart
> +      UrlService._launchUrl('https://play.google.com/store/apps/details?id=com.fedosov.mindtracker');
Создай константу
`static const String _googlePlayUrl = 'https://play.google.com/store/apps/details?id=com.fedosov.mindtracker';`

2022-11-28 17:17 UTC, fedosovmu commented on lib/src/domain/services/url_service.dart
> +      UrlService._launchUrl('https://apps.apple.com/us/app/mind-tracker-journal/id1564080533');
Тут тоже

2022-11-28 17:17 UTC, fedosovmu commented on lib/src/domain/services/cloud_firestore_service.dart
> +    print('testing');
print('testing'); удали

2022-11-28 17:17 UTC, fedosovmu commented on lib/src/domain/repositories/default_events_repository.dart
> +  static List<DefaultEvent> get allDefaultEvent => _allDefaultEvents;
Можно просто сделать _allDefaultEvents публичным, а не создавать новое поле

2022-11-28 17:38 UTC, fedosovmu commented on lib/main.dart
> +
Опять слишком много пробелов

2022-11-28 17:38 UTC, fedosovmu commented on lib/main.dart
> +
И здесь пробел. В пробелах нет ничего плохого. Но просто когда между какими-то провайдерами они есть, а между другими нет - код выглядит немного неоднородно.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/domain/entities/other/mood_assessment.dart
> +      _selectedUserEmotionsIds = selectedUserEmotions.map(
Лишняя **s** в слове Emotion**S**
`_selectedUserEmotionIds`
s ставится только один раз на конце, сколько бы слов ни шло до этого. Ну это так на будущее.
Почему так:
Потому что существительным является только последнее слово, а те которые перед ним это прилагательные.
В данном случае Emotion это прилагательное.
Selected emotion id - Выбранный эмоциональный идентификатор
Selected emotion ids - Выбранные эмоциональные идентификаторЫ.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/common_widgets/frequency_diagram/frequency_diagram.dart
> +          || moodAssessment.selectedInternalEmotions.contains(widget.event));
```
moodAssessment.selectedUserEvents.contains(widget.event) 
|| moodAssessment.selectedEmotions.contains(widget.event))
|| moodAssessment.selectedUserEmotions.contains(widget.event) // <---
```
Нужно добавить еще проверку на наличие пользовательских эмоций а не только встроенных.
Здесь мы пытаемся получить список оценок в которых есть выбранные нами Event. Поэтому проводить проверку нужно по всем полям: userEvents, internalEmotions и userEmotions.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/common_widgets/frequency_diagram/frequency_diagram.dart
> +    } else if (widget.event is InternalEmotion) {
`(widget.event is InternalEmotion) || (widget.event is UserEmotion)`
У нас наверняка еще много где есть куча подобных проверок. Поэтому я и предлагал создать абстрактный класс Emotion. И во всех подобных местах заменить InternalEmotion на Emotion. Чтобы не писать по два раза `object is InternalEmotion || object is UserEmotion` а писать просто `object is Emotion`

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/common_widgets/mood_assessment_card_list_view/widgets/mood_assessment_card.dart
> +      final partOfDay = 'part_of_day.${moodAssessment.partOfDay.index}'.tr();
О прикольно что заметил такую мелочь и исправил String на final. Молодец)

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/screens/main_screen/home_page/popups/emotion_popup.dart
> +              ),
Тут SizedBox-ы наверное лучше в одну строчку писать. А вообще проблема с форматированием она более глобальная чем может показаться. И если над проектом работает больше чем один человек лучше использовать автоформатирование. Чтобы все писали код в одном стиле. И чтобы не коммитить случайные изменения связанные с тем что кто-то запятую подвинул.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/screens/main_screen/home_page/popups/thankful_popup.dart
> +            'platform': Platform.isAndroid ? 'Google Play' : 'App Store'
Это лучше вынести в класс Content
`String get platformStoreName => Platform.isAndroid ? 'Google Play' : 'App Store';`
А здесь заменить на
`'platform': Content.platformStoreName`
Подобный кейс может еще встретиться в будущем

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/domain/viewmodels/emotion_providers/user_emotions_provider.dart
> +// import 'package:mind_tracker/src/domain/viewmodels/event_providers/default_events_provider.dart';
Не оставляй закомментированных кусков кода.
Есть только одно исключение если ты хочешь временно отключить какой-то функционал и поэтому комментируешь строчку кода который его включает.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/domain/viewmodels/emotion_providers/user_emotions_provider.dart
> +  // }
Здесь тоже нужно удалить.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/domain/viewmodels/event_providers/events_provider.dart
> +    // userEventsAndEmotions.sort();
Закомментированная строчка кода. Нужно удалить.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/screens/main_screen/home_page/popups/default_popup.dart
> +      alignment: position == null ? Alignment.bottomCenter : position,
А можно кстати вот так
`alignment: position ?? Alignment.bottomCenter`
Оператор ?? берет правое значение если левое равно null.
А если левое равно не null, тогда просто оставляет левое.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/screens/main_screen/home_page/popups/rate_popup.dart
> +    }
Здесь наверное лучше
`final pathToIcon = index >= rating ? CustomIconPaths.emptyStar : CustomIconPaths.star;`
А в самом виджете уже
`AssetImage(pathToIcon)`

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/screens/main_screen/home_page/popups/rate_popup.dart
> +typedef void RatingChangeCallback(int rating);
О клевая практика давать типы кэллбекам. Я таким к сожалению не пользовался) У меня все кэллбеки без указания типов)
И да я думаю это очень правильно что кэллбек объявляется в классе с виджетом. Потому что получается что если ты используешь данный виджет, то и тип кэллбека который тебе нужно в него передать ты уже импортировал вместе с виджетом.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/screens/main_screen/home_page/popups/rate_popup.dart
> +        onTap: onRatingChanged == null ? null : () => onRatingChanged(index + 1),
А у нас же onRatingChanged должен всегда передаваться разве нет?
Если он всегда передается можно тогда
`onTap: () => onRatingChanged(index + 1)`

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/screens/main_screen/home_page/popups/rate_popup.dart
> +class RatePopup extends StatefulWidget {
Два виджета лучше не объявлять в одном файле. StarRating лучше вынести в отдельный файл.

На самом деле есть еще один вариант о котором я сейчас расскажу просто чтобы ты знал.
Если второй виджет используется только внутри первого и больше нигде. Тогда можно добавить к его имени _. Типо `class _StarRating {`.
Модификатор _ ограничивает зону видимости тем файлом где объявлен данный класс переменная или метод.
То есть класс или переменную с префиксом _ нельзя будет использовать за пределами данного файла. Что является ожидаемым поведением, ведь _StarRating является частью RatePopup. И не планируется что он сможет использоваться отдельно как независимый виджет.

2022-11-28 17:38 UTC, fedosovmu commented on lib/generated/codegen_loader.g.dart
> +static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "ru": ru};
Странно. Почему-то русский и английский в данном файле поменялись местами. Но это скорее всего потому что я когда-то давно поставил в качестве основного языка английский, а не русский.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/utils/content/custom_icon_paths.dart
> +  static const closeIcon = '$_pathToOtherIcons/close_announce.png';
А крестик у попапа и карточки отличается? Этот крестик используется для закрытия карточки на главном экране правильно? Просто у нас уже есть иконка крестика, которая используется для закрытия попапа.

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/utils/content/custom_icon_paths.dart
> +  static const closeIcon = '$_pathToOtherIcons/close_announce.png';
Слово Icon нужно убрать из названия. Так как оно уже есть в названии класса CustomIconPaths.
Таким образом мы избегаем ненужного дублирования.
типо
`CustomIconPaths.close`
а не
`CustomIconPaths.closeIcon`

2022-11-28 17:38 UTC, fedosovmu commented on lib/src/views/utils/content/custom_icon_paths.dart
> +  static const newUpdateIconM = '$_pathToOtherIcons/big_update_emoji.png';
Слово `new` довольно опасное. Потому что все что является новым сейчас, перестанет быть новым когда-нибудь потом. Здесь наверное лучше emotionUpdate. Потому что текущий апдейт является апдейтом с эмоциями, а будущие будут называться как-нибудь по другому.

2022-11-28 17:43 UTC, fedosovmu requested changes

2022-11-28 17:43 UTC, fedosovmu commented on lib/src/domain/viewmodels/emotion_providers/user_emotions_provider.dart
> +}
Удали комментарий

2022-11-28 17:43 UTC, fedosovmu commented on lib/src/domain/viewmodels/emotion_providers/user_emotions_provider.dart
> +    // UserEventsLogger.deleteUserEvent();
Удали комментарий

2022-11-28 17:43 UTC, fedosovmu commented on lib/src/domain/viewmodels/emotion_providers/user_emotions_provider.dart
> +    // UserEventsLogger.updateUserEvent();
Удали комментарий

2022-11-28 17:43 UTC, fedosovmu commented on lib/src/domain/viewmodels/emotion_providers/user_emotions_provider.dart
> +    // UserEventsLogger.createCustomUserEvent();
Удали комментарий

2022-11-28 17:43 UTC, fedosovmu commented on lib/src/domain/viewmodels/data_providers/popup_provider.dart
> +      );
```
_settingsProvider.setParameter(
        name: _shownPopupIdsName,
        data: shownPopupIds.toList(),
      );
```
Можно вынести в метод `_updateShownPopupIds`
Код не должен повторяться. Даже два повторения уже повод вынести в отдельный метод.
Don't Repeat Yourself

2022-11-28 17:43 UTC, fedosovmu commented on lib/src/domain/viewmodels/data_providers/popup_provider.dart
> +    return;
Пустой `return;` не нужен.
Когда функция завершается она и так возвращает пустое значение.
Пустой ретурн нужен только если мы хотим завершить функцию раньше времени.

2022-11-28 17:43 UTC, fedosovmu commented on lib/src/domain/viewmodels/data_providers/popup_provider.dart
> +    shownPopupIds = shownPopupIdsMaps == null ? {} : shownPopupIdsMaps.toSet();
По идее можно вот так
`shownPopupIds = shownPopupIdsMaps?.toSet() ?? {};`

2022-11-28 17:43 UTC, fedosovmu commented on lib/src/domain/viewmodels/event_providers/events_provider.dart
> +  List<Event> get originalDefaultEvents => _defaultEventsProvider.allDefaultEvents;
Лучше сделать поле приватным
`_originalDefaultEvents`
Так как оно не используется за пределами класса.
И вообще по идее раз уж начал называть allDefaultEvents то так и продолжай везде во всех частях приложения
`_allDefaultEvents`

2022-11-28 19:13 UTC, fedosovmu commented on lib/src/views/ui_kit/buttons/standard_button.dart
> +            ) : widget.textStyle,
```
widget.textStyle ?? CustomTextStyles.buttonMedium.copyWith(
                color: widget.enabled ? CustomColors.white : CustomColors.purple5
            )
```

2022-11-30 18:54 UTC, fedosovmu approved these changes

2022-11-30 18:54 UTC, merged